trigger:
 branches:
   exclude:
    - feature/terraform-backend
   include:
     - master
pool:
  name: 'terraform-pool'
  demands:
    - terraform 

variables:
 Subscription: 

stages:
- stage: 
  jobs:
    - job: 'init'
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'ado-2-azure'
          backendAzureRmStorageAccountName: 'terrastatesa'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: "tfstate"
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'validate'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'ado-2-azure'